resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: {{pcf_pipelines_uri}}
    branch: {{pcf_pipelines_branch}}

- name: tile
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: {{product_slug}}
    product_version: {{product_version_regex}}
    sort_by: semver

- name: stemcell
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: {{stemcell_slug}}
    product_version: {{product_stemcell_version_regex}}
    sort_by: semver

jobs:
- name: upload-stemcell
  plan:
  - get: pcf-pipelines
  - get: stemcell
    trigger: true
    params:
      globs: [ {{stemcell_globs}} ]

  - task: upload-stemcell
    file: pcf-pipelines/tasks/upload-stemcell/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}

- name: upload-and-stage-tile
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      resource: tile
      trigger: true
      params:
        globs: [ {{product_globs}} ]

  - task: upload-tile-and-stemcell
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: {{iaas_type}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: ""
      OM_IP: ""


  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}

- name: apply-changes
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: stemcell
      passed: [ upload-stemcell ]
      trigger: true
      params:
        globs: [ {{stemcell_globs}} ]

    - get: pivnet-product
      resource: tile
      passed: [ upload-and-stage-tile ]
      trigger: true
      params:
        globs: [ {{product_globs}} ]

  - task: stage-stemcell
    file: pcf-pipelines/tasks/stage-stemcell/task.yml
    params:
      IAAS: {{iaas_type}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: ""
      OM_IP: ""


  - task: selective-deploy
    file: pcf-pipelines/tasks/selective-deploy/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
