---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS: ~
  OPSMAN_CLIENT_ID: ~
  OPSMAN_CLIENT_SECRET: ~
  DEBUG: 'false'

inputs:
  - name: stemcell
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/upload-stemcell/task.sh
