---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: pcf-pipelines

outputs:
  - name: diagnostic-report

params:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:

run:
  path: pcf-pipelines/tasks/export-opsmgr-diagnostic-report/task.sh
