# The IaaS name for which stemcell to download. This must match the IaaS name
# within the stemcell to download, e.g. "vsphere", "aws", "azure", "google" must be lowercase.
iaas_type: aws

# Operations Manager
# ------------------------------
# Credentials for Operations Manager. These are used for uploading, staging,
# and deploying the product file on Operations Manager.
# Either opsman_client_id/opsman_client_secret or opsman_admin_username/opsman_admin_password needs to be specified.
# If you are using opsman_admin_username/opsman_admin_password, edit opsman_client_id/opsman_client_secret to be an empty value.
# If you are using opsman_client_id/opsman_client_secret, edit opsman_admin_username/opsman_admin_password to be an empty value.
opsman_admin_username: ~
opsman_admin_password: ~
opsman_client_id: ((sandbox-opsman-client.username))
opsman_client_secret: ((sandbox-opsman-client.password))
opsman_domain_or_ip_address: ((sandbox-opsman.domain_or_ip_address))

# Resource
# ------------------------------
# The token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: ((pivnet_token))

# The globs regular expression for the PivNet resource to download the product
# release files. "*pivotal" is the default.
# For products such as ERT, it is recommended to use "cf*pivotal" to avoid the
# extra download of the SRT file in PCF 1.12.*
product_globs: "*pivotal"

# om-linux
# ------------------------------
# The name of the product on Pivotal Network. This is used to configure the
# resource that will fetch the product file.
#
# This can be found in the URL of the product page, e.g. for rabbitmq the URL
# is https://network.pivotal.io/products/pivotal-rabbitmq-service, and the
# product slug is 'pivotal-rabbitmq-service'.
product_slug: ~

# The minor product version to track, as a regexp. To track 1.11.x of a product, this would be "^2\.0\.[0-9]+$", as shown below.
product_version_regex: ~

# Slug for PCF Stemcells. Basically don't touch this.
stemcell_slug: "stemcells"

# Match the stemcell glob pattern for your IaaS. This value will be the same as iaas_type, except with *'s around it.
stemcell_globs: "*aws*"

# Basically don't touch this.
pcf_pipelines_uri: https://github.com/aegershman/pcf-pipelines-selective-deploy.git
pcf_pipelines_branch: master
