---
platform: linux

image_resource:
    type: docker-image
    source:
        repository: czero/cflinuxfs2

inputs:
    - name: pcf-pipelines
    - name: pivnet-product

params:
    OPSMAN_CLIENT_ID: ~
    OPSMAN_CLIENT_SECRET: ~
    OPSMAN_DOMAIN_OR_IP_ADDRESS: ~
    DEBUG: 'false'

run:
    path: pcf-pipelines/tasks/selective-deploy/task.sh
